primary_source:
  repository: "Church History Library, Salt Lake City"
  collection: "Hyrum Smith Papers"
  catalog_record: "MS 9028446"
  url: "https://catalog.churchofjesuschrist.org/record/9028446a-7042-4f5b-8af1-eb886fce0b0c"
rights:
  text_and_metadata: "CC BY-NC 4.0 (this digital edition)"
  images: "Subject to holding institution’s terms of use"
editor:
  name: "Mark Phillips"
  edition: "2025 Digital Edition"
  location: "Mesa, Arizona"